default_platform(:android)

platform :android do
  desc "Promote to Internal"
    lane :upload_to_internal do
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        # release_status: "draft" -> defaults to "completed"
      )
    end
end