name: PassaParola - CI/CD pipeline for Android
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest #macos-latest
    steps:
      - uses: actions/checkout@v3
        # with:
          # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: "stable"

      - uses: dart-lang/setup-dart@v1.3

      - run: flutter --version
        env:
          KEY_JKS: ${{ secrets.RELEASE_KEYSTORE }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEYSTORE_PASSWORD_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Create key.properties
        run: |
          touch android/key.properties
          echo "storePassword=<storePassword>
          keyPassword=<keyPassword>
          keyAlias=<keyAlias>
          storeFile=../key.jks"  > ./android/key.properties

      - name: Get dependencies
        run: flutter pub get

      # - name: Build .g files
      #   run: flutter pub run build_runner build --delete-conflicting-outputs

      # - name: Run Dart analyzer
      #   run: flutter analyze

      # - name: Run Tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk

      - uses: actions/upload-artifact@v1      
        with:        
          name: release-apk        
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build APPBUNDLE
        run: flutter build appbundle --release

      - name: Sign APPBUNDLE
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE }}
          alias: ${{ secrets.KEYSTORE_PASSWORD_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      
      - uses: actions/upload-artifact@v1      
        with:        
          name: release-appbundle        
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APPBUNDLE with Fastlane
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: upload_to_internal 
          subdirectory: android #mention if the fastlane folder is inside the android folder.

      - name: Get app version
        id: version
        run: echo "::set-output name=version::$(grep "version" pubspec.yaml | tr -cd '[0-9]+)\.([0-9]+)\.([0-9]+)+([0-9]+)')"
      
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.version.outputs.version }}-staging"
          message: "Increment version to ${{ steps.version.outputs.version }}"
      
